sudo: false
language: node_js
node_js: "5"
install:        npm install -g gulp gulp-cli
before_script:  node --version && npm --version && bower --version && gulp --version
script:         npm install && bower install && ./setEnvironment.sh && gulp build
