language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
  - develop
env:
  global:
  - PACKAGE="vamp-ui"
  - UI_VERSION="0.7.9"
  - DISTRIBUTABLE="${PACKAGE}-${UI_VERSION}-${TRAVIS_BUILD_NUMBER}"
  - secure: OLfqWw7kfWxjuyPi42e5mpd1hQCaUMYMrvF7qlnu5PvT4U4Hl92WARaPUouN10rxe17AtzNQw/g8g9+w/REP0axwyiQbjqM9qDe1yNm8DfyaNwDrSgj/G4mXbTAOFx9BqIRBKsI6coWZvbD6O5piWp87Tpi0drJq2XP1wGyx5m8=
  - secure: SitulVd3T2atQ85iI+zDMElze5IOBRkdxGQjB97oDnPYrkyACtQhCZRmYgQ4uHzb0xKuh1s0hLyQ8VnmS3qzsUjHC2X2KOTl399q9tz7zcvswCjWWl1QQzTIrgcnxWGi6Xp1gus475dgh+saEhFbVLHIlkhnajC542OhKCRtpX0=
  - secure: UvwcnAMeBzgHglWGyujM+IBjXNC6/gLkPgym8ynVIn+evFRdMDXGGVJ3ksDJsEppA6dMuwJSHTOJ/DjkkSXC5fHajhnb6S4zLz/J0R47cSdVHE37N3ciP+tlFhk9J7vf0/qbwcHaEWRhAqx4dxzG8XcFMu1f1qpCKb7GI7Fv9iI=
before_install: gem install compass
script:
- echo Building version ${UI_VERSION}-$TRAVIS_BUILD_NUMBER of ${PACKAGE}
- if [ ! -d "build" ];
  then mkdir build
  ; fi
- echo "window.mixpanelToken = \"$MIXPANEL_TOKEN\"" > build/token.js
- gulp build
- gulp dist
- mv build vamp-ui
- jar cvf ${DISTRIBUTABLE}.jar vamp-ui/
after_success:
- test ${TRAVIS_PULL_REQUEST} == "false" && if [[ ${TRAVIS_BRANCH} == "develop" ]];
  then curl -T ${DISTRIBUTABLE}.jar -u${BINTRAY_USER}:${BINTRAY_API_KEY} -H "X-Bintray-Package:${PACKAGE}"
  -H "X-Bintray-Version:${UI_VERSION}" -H "X-Bintray-Publish:1"  https://api.bintray.com/content/magnetic-io/downloads/${PACKAGE}/${DISTRIBUTABLE}-dev.jar;
  else curl -T ${DISTRIBUTABLE}.jar -u${BINTRAY_USER}:${BINTRAY_API_KEY} -H "X-Bintray-Package:${PACKAGE}"
  -H "X-Bintray-Version:${UI_VERSION}" -H "X-Bintray-Publish:1"  https://api.bintray.com/content/magnetic-io/downloads/${PACKAGE}/${DISTRIBUTABLE}.jar
  ; fi
notifications:
  slack:
    secure: LZ3Nn9cExIslnwGdwHLzAHXAV7gtX9gxaFFFUd1AVaD58Z4X177FwgH4J3g9jKMA3uLLx4CpWNkEWeMMRz/1rcX2V8Q80n8fIv58+zaMZ6UPzDWyN2dYc9mSxZOlsKkricSAQxNeAjdkrcuBf95pyNHp/34H/RVJ74CaYRxqYjg=
