sudo: false
language: node_js
node_js: 6
install: npm install -g "gulpjs/gulp#4.0"
before_script: gulp --version
script: npm install && bower install && ./environment.sh && gulp build
after_success: |
  if [ -n "TRAVIS_TAG" ] && [ "$(git describe --tags)" = "$(git describe --abbrev=0)" ]; then
    bash $TRAVIS_BUILD_DIR/.travis-bintray.sh
  fi
env:
  global:
  - secure: W9FXH6pS0MHTW2Nisi4FbCrnc+07s9eg2frxY3Qw6IAC3HxxnKf0Gcobe34fAmQ4Nl6RWaqpNXGTKPta3PjDWaOWk9fM5dATyvUUMbfecwpNQUx5ZRwNuAAnc30L69HdSv8rIdnTOSLBOv8AT8g0YNHaQUdUwOVACzciN6wQxlI=
  - secure: BXmHHNt1Zw+OQyduUlxldlXSc4P3b65OM/XWHhDL93lAtaN6ozfhswxl5aFK807zJiY1xFpjVZsKbaPp5Zjm/Igew5KisHjcyo90jQbquN9UNzMhpZsEUf1fcfG4BPE5XLfx0121O2i3QMbyutQz5AhHOLfTnieNlf2FsrLQfZ0=
