language: node_js
node_js:
- '0.11'
env:
  global:
  - secure: "I5psJNRU2k/pBXYAhHA5tfG+7LP3K5c2Gaf+Jr1pcUt9MimKu/QNZzVrzM4GLGPOQ3XkGfMZK4ixn3ihHZdl2Ak/Fs4c9pdMOqYFRIA8pYYgRYcxuRVJcEDbMDZiBRPUsWG4epMwPG7e5+4j2x6BiLCyV70cEcv9v/RKcSrx8Tk="
  - secure: "Dl8OVvgZurFtflsm4VCEr93UrqqP9ssdGz11/FWHcCbG407rMrBAIKrVjUEdDTRJ7VlTmre75ZZlrDTz8OA9XTwzwMzwOsWQVCLo+RGQoPTUQXXXJyKnrMmQcVUlCCLhaG3hP3y6IlDfXoR75romZqft4W6MuRrrVdVKSQBu0Fk="
- UI_VERSION=0.0.2-$TRAVIS_JOB_ID
script:
- gulp dist
- mv build vamp-ui
- jar cvf ../vamp-ui-$UI_VERSION.jar vamp-ui/
after_success:
- test ${TRAVIS_PULL_REQUEST} == "false" && test ${TRAVIS_BRANCH} == "develop" &&
  curl -T ../vamp-ui-$UI_VERSION.jar -u$BINTRAY_API_USER:$BINTRAY_API_KEY https://api.bintray.com/content/magnetic-io/vamp/vamp-ui/$UI_VERSION/

